In [1]:
import sqlite3
import pymongo

In [16]:
myclient = pymongo.MongoClient("mongodb+srv://dwight:u8hze1XIB74QFkyb@cluster0-3q1mp.mongodb.net/test?retryWrites=true&w=majority")

In [17]:
mydb = myclient['dwight']

In [68]:
mycol = mydb['rpg']

In [10]:
conn = sqlite3.connect('rpg_db.sqlite3')

In [11]:
cur = conn.cursor()

In [5]:
cur.execute("""
    SELECT * FROM armory_weapon LIMIT 10;
""")
conn.commit()

In [65]:
lst = []

for row in cur.execute(f"""
    SELECT * 
    FROM armory_item
    """):
    lst.append({'item_id': row[0], 'name': row[1], 'value': row[2],'weight': row[3]})
    
conn.commit()

In [72]:
mycol = mydb['armory_item']

In [74]:
items = mycol.insert_many(lst)

In [75]:
lst = []

for row in cur.execute(f"""
    SELECT * 
    FROM armory_weapon
    """):
    lst.append({'item_ptr_id': row[0], 'power': row[1]})
    
conn.commit()

In [79]:
mycol = mydb['armory_weapon']
items = mycol.insert_many(lst)

In [214]:
lst = []

for row in cur.execute(f"""
    SELECT * 
    FROM charactercreator_character_inventory
    """):
    lst.append({'id': row[0], 'character_id': row[1], 'item_id': row[2]})
    
conn.commit()
mycol = mydb['charactercreator_character_inventory']
items = mycol.insert_many(lst)

In [81]:
lst = []

for row in cur.execute(f"""
    SELECT * 
    FROM charactercreator_character
    """):
    lst.append({'character_id': row[0], 
                'name': row[1], 
                'level': row[2], 
                'exp': row[3], 
                'hp': row[4], 
                'strength': row[5], 
                'intelligence': row[6], 
                'dexterity': row[7], 
                'wisdom': row[8]})
    
conn.commit()

In [82]:
mycol = mydb['charactercreator_character']
items = mycol.insert_many(lst)

In [215]:
lst = []

for row in cur.execute(f"""
    SELECT * 
    FROM charactercreator_cleric
    """):
    lst.append({'character_ptr_id': row[0], 'using_shield': row[1], 'mana': row[2]})
    
conn.commit()
mycol = mydb['charactercreator_cleric']
items = mycol.insert_many(lst)

In [216]:
lst = []

for row in cur.execute(f"""
    SELECT * 
    FROM charactercreator_fighter
    """):
    lst.append({'character_ptr_id': row[0], 'using_shield': row[1], 'rage': row[2]})
    
conn.commit()
mycol = mydb['charactercreator_fighter']
items = mycol.insert_many(lst)

In [84]:
names = list(map(lambda x: x[0], cur.description))
names

['character_id',
 'name',
 'level',
 'exp',
 'hp',
 'strength',
 'intelligence',
 'dexterity',
 'wisdom']

In [241]:
def insertTable(x):
    lst = []
    for row in cur.execute(f"""
        SELECT * 
        FROM {x}
        """):
        names = list(map(lambda x: x[0], cur.description))

        for name in names: 
            lst.append({names[i]: row[i]})

    #     names = list(map(lambda x: x[0], cur.description))

    #     for name in names: 
    #         lst.append({name: 'hey'})

    conn.commit()

In [242]:
lst

[{'character_id': 1},
 {'character_id': 2},
 {'character_id': 3},
 {'character_id': 4},
 {'character_id': 5},
 {'character_id': 6},
 {'character_id': 7},
 {'character_id': 8},
 {'character_id': 9},
 {'character_id': 10},
 {'character_id': 11},
 {'character_id': 12},
 {'character_id': 13},
 {'character_id': 14},
 {'character_id': 15},
 {'character_id': 16},
 {'character_id': 17},
 {'character_id': 18},
 {'character_id': 19},
 {'character_id': 20},
 {'character_id': 21},
 {'character_id': 22},
 {'character_id': 23},
 {'character_id': 24},
 {'character_id': 25},
 {'character_id': 26},
 {'character_id': 27},
 {'character_id': 28},
 {'character_id': 29},
 {'character_id': 30},
 {'character_id': 31},
 {'character_id': 32},
 {'character_id': 33},
 {'character_id': 34},
 {'character_id': 35},
 {'character_id': 36},
 {'character_id': 37},
 {'character_id': 38},
 {'character_id': 39},
 {'character_id': 40},
 {'character_id': 41},
 {'character_id': 42},
 {'character_id': 43},
 {'character_id': 44},
 {'character_id': 45},
 {'character_id': 46},
 {'character_id': 47},
 {'character_id': 48},
 {'character_id': 49},
 {'character_id': 50},
 {'character_id': 51},
 {'character_id': 52},
 {'character_id': 53},
 {'character_id': 54},
 {'character_id': 55},
 {'character_id': 56},
 {'character_id': 57},
 {'character_id': 58},
 {'character_id': 59},
 {'character_id': 60},
 {'character_id': 61},
 {'character_id': 62},
 {'character_id': 63},
 {'character_id': 64},
 {'character_id': 65},
 {'character_id': 66},
 {'character_id': 67},
 {'character_id': 68},
 {'character_id': 69},
 {'character_id': 70},
 {'character_id': 71},
 {'character_id': 72},
 {'character_id': 73},
 {'character_id': 74},
 {'character_id': 75},
 {'character_id': 76},
 {'character_id': 77},
 {'character_id': 78},
 {'character_id': 79},
 {'character_id': 80},
 {'character_id': 81},
 {'character_id': 82},
 {'character_id': 83},
 {'character_id': 84},
 {'character_id': 85},
 {'character_id': 86},
 {'character_id': 87},
 {'character_id': 88},
 {'character_id': 89},
 {'character_id': 90},
 {'character_id': 91},
 {'character_id': 92},
 {'character_id': 93},
 {'character_id': 94},
 {'character_id': 95},
 {'character_id': 96},
 {'character_id': 97},
 {'character_id': 98},
 {'character_id': 99},
 {'character_id': 100},
 {'character_id': 101},
 {'character_id': 102},
 {'character_id': 103},
 {'character_id': 104},
 {'character_id': 105},
 {'character_id': 106},
 {'character_id': 107},
 {'character_id': 108},
 {'character_id': 109},
 {'character_id': 110},
 {'character_id': 111},
 {'character_id': 112},
 {'character_id': 113},
 {'character_id': 114},
 {'character_id': 115},
 {'character_id': 116},
 {'character_id': 117},
 {'character_id': 118},
 {'character_id': 119},
 {'character_id': 120},
 {'character_id': 121},
 {'character_id': 122},
 {'character_id': 123},
 {'character_id': 124},
 {'character_id': 125},
 {'character_id': 126},
 {'character_id': 127},
 {'character_id': 128},
 {'character_id': 129},
 {'character_id': 130},
 {'character_id': 131},
 {'character_id': 132},
 {'character_id': 133},
 {'character_id': 134},
 {'character_id': 135},
 {'character_id': 136},
 {'character_id': 137},
 {'character_id': 138},
 {'character_id': 139},
 {'character_id': 140},
 {'character_id': 141},
 {'character_id': 142},
 {'character_id': 143},
 {'character_id': 144},
 {'character_id': 145},
 {'character_id': 146},
 {'character_id': 147},
 {'character_id': 148},
 {'character_id': 149},
 {'character_id': 150},
 {'character_id': 151},
 {'character_id': 152},
 {'character_id': 153},
 {'character_id': 154},
 {'character_id': 155},
 {'character_id': 156},
 {'character_id': 157},
 {'character_id': 158},
 {'character_id': 159},
 {'character_id': 160},
 {'character_id': 161},
 {'character_id': 162},
 {'character_id': 163},
 {'character_id': 164},
 {'character_id': 165},
 {'character_id': 166},
 {'character_id': 167},
 {'character_id': 168},
 {'character_id': 169},
 {'character_id': 170},
 {'character_id': 171},
 {'character_id': 172},
 {'character_id': 173},
 {'character_id': 174},
 {'character_id': 175},
 {'character_id': 176},
 {'character_id': 177},
 {'character_id': 178},
 {'character_id': 179},
 {'character_id': 180},
 {'character_id': 181},
 {'character_id': 182},
 {'character_id': 183},
 {'character_id': 184},
 {'character_id': 185},
 {'character_id': 186},
 {'character_id': 187},
 {'character_id': 188},
 {'character_id': 189},
 {'character_id': 190},
 {'character_id': 191},
 {'character_id': 192},
 {'character_id': 193},
 {'character_id': 194},
 {'character_id': 195},
 {'character_id': 196},
 {'character_id': 197},
 {'character_id': 198},
 {'character_id': 199},
 {'character_id': 200},
 {'character_id': 201},
 {'character_id': 202},
 {'character_id': 203},
 {'character_id': 204},
 {'character_id': 205},
 {'character_id': 206},
 {'character_id': 207},
 {'character_id': 208},
 {'character_id': 209},
 {'character_id': 210},
 {'character_id': 211},
 {'character_id': 212},
 {'character_id': 213},
 {'character_id': 214},
 {'character_id': 215},
 {'character_id': 216},
 {'character_id': 217},
 {'character_id': 218},
 {'character_id': 219},
 {'character_id': 220},
 {'character_id': 221},
 {'character_id': 222},
 {'character_id': 223},
 {'character_id': 224},
 {'character_id': 225},
 {'character_id': 226},
 {'character_id': 227},
 {'character_id': 228},
 {'character_id': 229},
 {'character_id': 230},
 {'character_id': 231},
 {'character_id': 232},
 {'character_id': 233},
 {'character_id': 234},
 {'character_id': 235},
 {'character_id': 236},
 {'character_id': 237},
 {'character_id': 238},
 {'character_id': 239},
 {'character_id': 240},
 {'character_id': 241},
 {'character_id': 242},
 {'character_id': 243},
 {'character_id': 244},
 {'character_id': 245},
 {'character_id': 246},
 {'character_id': 247},
 {'character_id': 248},
 {'character_id': 249},
 {'character_id': 250},
 {'character_id': 251},
 {'character_id': 252},
 {'character_id': 253},
 {'character_id': 254},
 {'character_id': 255},
 {'character_id': 256},
 {'character_id': 257},
 {'character_id': 258},
 {'character_id': 259},
 {'character_id': 260},
 {'character_id': 261},
 {'character_id': 262},
 {'character_id': 263},
 {'character_id': 264},
 {'character_id': 265},
 {'character_id': 266},
 {'character_id': 267},
 {'character_id': 268},
 {'character_id': 269},
 {'character_id': 270},
 {'character_id': 271},
 {'character_id': 272},
 {'character_id': 273},
 {'character_id': 274},
 {'character_id': 275},
 {'character_id': 276},
 {'character_id': 277},
 {'character_id': 278},
 {'character_id': 279},
 {'character_id': 280},
 {'character_id': 281},
 {'character_id': 282},
 {'character_id': 283},
 {'character_id': 284},
 {'character_id': 285},
 {'character_id': 286},
 {'character_id': 287},
 {'character_id': 288},
 {'character_id': 289},
 {'character_id': 290},
 {'character_id': 291},
 {'character_id': 292},
 {'character_id': 293},
 {'character_id': 294},
 {'character_id': 295},
 {'character_id': 296},
 {'character_id': 297},
 {'character_id': 298},
 {'character_id': 299},
 {'character_id': 300},
 {'character_id': 301},
 {'character_id': 302}]